# Important Notes:
# Every field you add must be added to build.gradle expandProps map.


# Project
version=1.0.0.0
using_loaders=fabric,neoforge
group=com.wanomaniac.economy
java_version=21
mc_version=1.21.8
mod_name=Wano's Economy
mod_author=wanomaniac
mod_id=wanoeconomy
license=CC0-1.0
credits=wanomaniac
description=A economy mod for both client side and server side
modrinthID = u0KOoAQj
#USE_ENV_PLEASE_FOR_YOUR_SAFETY
modrinthTOKEN =
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=false
